GET http://localhost:3000/users


###


GET http://localhost:3000/users/12


####


POST http://localhost:3000/users/
Content-Type: application/json

{
  "name": "Alan Vega"
}


###


GET http://localhost:3000/users/5efa0b3bdf8bc4527f1abc08


###


DELETE http://localhost:3000/users/5efa0b3bdf8bc4527f1abc08


###